### ISSUE TITLE
[FEATURE REQUEST] Graceful Shutdown

### ISSUE THREAD

**Issue by changwuf31** [temporalio/roadrunner-temporal#34]
Hi, Is graceful shutdown implemented already for the temporal plugin ?

**Comment by wolfy-j** [comment]
Yes, it does. The plugin will attempt to complete in-flight activities before shutting down. However, under load, some workflow tasks might miss the worker, which is fine since the server will handle it properly.

**Comment by wolfy-j** [comment]
Graceful shutdown use similar behavior as hot reload command `rr reset`.

**Comment by changwuf31** [comment]
so, does that mean, we can use this on kubernetes:
```
lifecycle:
  preStop:
    exec:
      command: [
        # Gracefully shutdown roadrunner temporal
        "rr", "reset"
      ]
```
