### ISSUE TITLE
Is there a maxJobs or memoryLimit parameter ?

### ISSUE THREAD

**Issue by changwuf31** [temporalio/roadrunner-temporal#35]
Hi, as the title, are those params available already for the temporal plugin ?

**Comment by wolfy-j** [comment]
Yes, they are available via pool configuration:

```yaml
temporal:
    activities:
        num_workers: 4
        # default 0 - no limit
        max_jobs: 0
        # default 1 minute
        allocate_timeout: 60s
        # default 1 minute
        destroy_timeout: 60s
        # supervisor used to control http workers
        supervisor:
          # watch_tick defines how often to check the state of the workers (seconds)
          watch_tick: 1s
          # ttl defines maximum time worker is allowed to live (seconds)
          ttl: 0
          # idle_ttl defines maximum duration worker can spend in idle mode after first use. Disabled when 0 (seconds)
          idle_ttl: 10s
          # exec_ttl defines maximum lifetime per job (seconds)
          exec_ttl: 10s
          # max_worker_memory limits memory usage per worker (MB)
          max_worker_memory: 100
```

You can use the same config as for HTTP pool.
