### ISSUE TITLE
[🐛 BUG]: broken load balancing for workflow worker

### ISSUE THREAD

**Issue by CheAlex** [temporalio/roadrunner-temporal#383]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

In the test application [https://github.com/temporalio/samples-php](https://github.com/temporalio/samples-php), two related problems appear:
* broken load balancing - basically only `workflow` worker works
* no way to set limits for `workflow` worker

In the test application, running in docker, I added limits (`max_jobs`, `ttl`, `max_worker_memory`):
```
version: "2.7"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php worker.php"

temporal:
  address: "temporal:7233"
  activities:
    num_workers: 4
    max_jobs: 20
    supervisor:
      ttl: 180s # 3 minutes
      max_worker_memory: 80

logs:
  level: debug
  mode: development
```

these limits work correctly for `activity` workers and do not apply to `workflow` worker. As a result, the `workflow` worker lives forever, has memory leaks and does not restart automatically:
```
Workers of [temporal]:
+---------+-----------+---------+---------+---------+--------------------+
|   PID   |  STATUS   |  EXECS  | MEMORY  |  CPU%   |      CREATED       |
+---------+-----------+---------+---------+---------+--------------------+
|   31006 | ready     |   1,053 | 134 MB  |    0.47 | 10 hours ago       |
|   33611 | working   |      14 | 61 MB   |    0.12 | 2 minutes ago      |
|   33614 | working   |      14 | 61 MB   |    0.12 | 2 minutes ago      |
|   33612 | working   |      14 | 62 MB   |    0.11 | 2 minutes ago      |
|   33613 | working   |      14 | 61 MB   |    0.12 | 2 minutes ago      |
+---------+-----------+---------+---------+---------+--------------------+
```

I was looking for the ability to set limits for the `workflow` worker, but did not find it. Did I search badly?

Also, according to the statistics, there is a clear bias in the load towards the `workflow` worker

### Version

2.12.3
