### ISSUE TITLE
[Bug] Unable to start with only one worker (for xdebuging)

### ISSUE THREAD

**Issue by Rastusik** [temporalio/roadrunner-temporal#72]
**Describe the bug**
When using this .rr.yaml configuration:
```yaml
temporal:
  address: ${TEMPORAL_CLI_ADDRESS}
  namespace: ${TEMPORAL_NAMESPACE}
  activities:
    num_workers: 1
```
I'm seeing 2 php worker processes running. That is quite unfortunate when I'm trying to debug activities execution, since the two are competing for tasks and I'm only able to debug one worker at a time.

**To Reproduce**
1. set num_workers to 1 in your .rr.yaml
2. run `rr serve -c .rr.yaml`
3. Look in the process list (top or ps -aux) and see two workers running

**Expected behavior**
One worker should be running soI would be able to connect to the one which does the processing.

**Screenshots/Terminal ouput**
If applicable, add screenshots or code blocks to help explain your problem. You can also use [Loom](http://loom.com/) to do short, free video bug reports.

**Versions (please complete the following information where relevant):**
 - OS: Linux (Ubuntu from Docker)
 - Temporal Version: 1.10.2
 - are you using Docker or Kubernetes or building Temporal from source? Docker
